### ISSUE TITLE
[Request] Don't remove junk data from ISO

### ISSUE THREAD

**Issue by extherian** [RenaKunisaki/StarFoxAdventures#1]
This can easily be done using a third party tool like nkit, and need not be done using the Amethyst script. I suspect your alterations to the ISO structure may be partly what's causing this mod to crash so often, as it tends to happen when I'm moving between areas. At the very least, it would be nice if it was made optional somehow.

**Comment by RenaKunisaki** [comment]
By junk data what do you mean exactly? There's some padding between the header and the filesystem, and then there's empty space after the last file padding it to 1.5GB. Neither are ever used by the game.

Since the script has to build a new ISO from scratch (since files are added/removed/changed size) it just doesn't add this padding at the end. I can add that option but I don't think it will help anything.

I've been able to play through the entire game without any crashing. Can you give more information about the crashes you've experienced? Especially screenshots of the error screen? Are you using the debug/free move functions at all? This game does tend to be fragile at times, and can crash just because you flew over an invisible trigger or warped at the wrong time.

**Comment by extherian** [comment]
I managed to rebuild a full size ISO using GCTool, which I'll try using to see if it helps. Dolphin's developers mentioned stripping out the unused sectors of the ISO can mess with how Dolphin does disc reads, which is why I suspected it. The path to Cape Claw consistently crashes for me on Dolphin version 5.0-13495, but only when I'm on my way back to Thorntail Hollow. I tried compiling the development version 1.7 and I couldn't enter the Volcano Force Point Temple without it crashing. Music keeps laying, just the screen freezes and you can't move. 

Out of interest, are you playing on an actual GameCube? I'll try the Cape Claw route with the debug screens on, just in case it turns out to be an emulator problem.

**Comment by RenaKunisaki** [comment]
I mostly play on emulator but I do test on a Wii before each release.

Can you attach your save file? I have seen cases where a save file becomes bugged somehow.

**Comment by extherian** [comment]
Sure thing. By the way, there are a lot of debug settings I can toggle. Should I turn them all on while playing to see what happens when I crash, or do I only need one or two? 

[01-GSAE-Star Fox Adventures.zip](https://github.com/RenaKunisaki/StarFoxAdventures/files/5884183/01-GSAE-Star.Fox.Adventures.zip)

**Comment by RenaKunisaki** [comment]
If you're using the latest development builds, some of the debug settings can actually be unstable. The crash screen should tell everything important, so you might try turning them off.

**Comment by RenaKunisaki** [comment]
Okay, I've been able to reproduce the crash using that save file. Something is causing an out-of-memory condition. I've seen this before, but I'm not yet sure what exactly causes it.

**Comment by extherian** [comment]
I tried running through the Cape Claw route from Thorntail Hollow using Amethyst Edition 1.6 and revision 8ed7f3e. On both versions, it hangs in the pond that you have to swim through, but on 1.6 it only hangs for a couple of seconds and then you can move again, while on 8ed7f3e it hangs permanently and never recovers. Playing with 'Speed up Disc Transfer Rate' on makes the hang last for only a split second on 1.6 but doesn't prevent hangs on 8ed7f3e. If 'Use Panic Handlers' is ticked in Dolphin, then it will sometimes complain about invalid reads occurring. 

That pond appears to be a loading zone for the next area. At a wild guess, perhaps memory fragmentation is preventing the data that needs to load from fitting into memory? Possibly because of some change made to how the features you added to the game load into memory? I have no experience with low-level programming, so I'm just speculating here.

**Comment by RenaKunisaki** [comment]
I've changed the build script to not remove padding. I'll make a separate issue for the crash.
