### ISSUE TITLE
Crash when entering Arwing to Cloudrunner Fortress

### ISSUE THREAD

**Issue by extherian** [RenaKunisaki/StarFoxAdventures#2]
The game freezes with a loud buzzing sound when pressing a to enter the Arwing to reach Cloudrunner Fortress, Dolphin 5.0-13590. This time I had the debug text on, as seen in the attached image. This is v1.7, I think the ba40049 build, I forget exactly which one but it was one of the commits from January that I compiled. 
![Capture](https://user-images.githubusercontent.com/25255723/106275089-378d7580-622d-11eb-962f-662c0b5966a1.PNG)

**Comment by RenaKunisaki** [comment]
Is there no error message shown? Can you upload the dolphin.ini and gfx.ini from Dolphin's settings?

**Comment by extherian** [comment]
Never mind, I figured out what was causing it, it was my ISO size. GCRebuilder doesn't seem to put the image back together correctly. Sorry to waste your time.
