### ISSUE TITLE
Picking up the staff at the start of the game broken in 1.7

### ISSUE THREAD

**Issue by extherian** [RenaKunisaki/StarFoxAdventures#4]
The attached frame dump shows this bug in action. The cutscene audio continues to play, but the cutscene itself never plays, and you can't pick up the staff by pressing A.

https://user-images.githubusercontent.com/25255723/107648525-56036000-6c74-11eb-8ea2-a31a75acfb39.mp4

I have confirmed that this bug doesn't happen on version 1.6.

**Comment by RenaKunisaki** [comment]
Looks like it's caused by skipping the Arwing section. There must be a flag I overlooked there.
