### ISSUE TITLE
Some areas fail to load correctly

### ISSUE THREAD

**Issue by extherian** [RenaKunisaki/StarFoxAdventures#5]
After skipping the Arwing section from Cloudrunner Fortress, I found that the path leading to Lightfoot Village did not load, with an empty void where it should be. 

https://user-images.githubusercontent.com/25255723/107850537-07340280-6dfb-11eb-9fd2-3324472b22a0.mp4

**Comment by RenaKunisaki** [comment]
That might be an issue with the skip function, or an out of memory problem. In the latter case, saving and resetting might help.

You might be able to force it to load by standing at the edge and turning around to put the camera into the void area. You can also use Free Move to escape when you're stuck there.

**Comment by extherian** [comment]
It happened to me again in the exact same place when returning from the Walled City, so it may well be caused by Arwing skipping, which I've been using.

**Comment by RenaKunisaki** [comment]
This particular area does seem prone to memory issues for some reason. I'm not sure there's much I can do about it other than general optimization.

**Comment by RenaKunisaki** [comment]
Does this still happen after 5c0dec0cddd92fa6f46b8b8bfd7c20ec3b123ec9?

**Comment by extherian** [comment]
Nope, issue has been resolved.
