### ISSUE TITLE
Staff Booster doesn't boost high enough in some places

### ISSUE THREAD

**Issue by extherian** [RenaKunisaki/StarFoxAdventures#6]
For example, this ledge in the Ocean Force Point Temple is inaccessible on 1.7:

https://user-images.githubusercontent.com/25255723/107854341-26d72500-6e13-11eb-8932-d1622efe7840.mp4

On the original version of the game, the animation plays out like this:

https://user-images.githubusercontent.com/25255723/107854356-37879b00-6e13-11eb-8bc0-d6e56fc4f64b.mp4

**Comment by RenaKunisaki** [comment]
Can you reach it by switching to Fox? There's a spot in Dragon Rock that only Fox can reach. Hoping to fix these for v1.8.

**Comment by extherian** [comment]
Nope, Fox falls back down in exactly the same way as Krystal. I wonder if speeding up the Staff Booster animation caused it.

**Comment by RenaKunisaki** [comment]
I didn't change that animation, so that's odd.

**Comment by extherian** [comment]
The speed booster animation is twice as fast in this mod as it is in the vanilla game, which is what I was referring to. I've never fallen short on any other boost pad, just this specific one.

**Comment by extherian** [comment]
Never mind, turns out this does happen in other places, I've just had it happen to me at the Boost pad in the Hightop's room on Dragon Rock. As you can see from this video, it affects Fox as well, so it's not the character model that's the issue:

https://user-images.githubusercontent.com/25255723/107879717-687ad500-6ed2-11eb-8d3c-c5d619c8d04a.mp4

Here is what is supposed to happen in the vanilla game: 

https://user-images.githubusercontent.com/25255723/107880003-0d49e200-6ed4-11eb-9d32-e3db6004c060.mp4

**Comment by RenaKunisaki** [comment]
I see, the "faster climbing speed" patch inadvertently changed that animation.
